# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lizilin/projects/CPUStallSim/thirdparty/CPUDelayViewer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lizilin/projects/CPUStallSim/thirdparty/CPUDelayViewer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lizilin/projects/CPUStallSim/thirdparty/CPUDelayViewer/CMakeFiles /home/lizilin/projects/CPUStallSim/thirdparty/CPUDelayViewer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lizilin/projects/CPUStallSim/thirdparty/CPUDelayViewer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/lizilin/projects/CPUStallSim/thirdparty/CPUDelayViewer/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CPUDelayViewer

# Build rule for target.
CPUDelayViewer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CPUDelayViewer
.PHONY : CPUDelayViewer

# fast build rule for target.
CPUDelayViewer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/build
.PHONY : CPUDelayViewer/fast

#=============================================================================
# Target rules for targets named CPUDelayViewer_autogen

# Build rule for target.
CPUDelayViewer_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CPUDelayViewer_autogen
.PHONY : CPUDelayViewer_autogen

# fast build rule for target.
CPUDelayViewer_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer_autogen.dir/build.make CMakeFiles/CPUDelayViewer_autogen.dir/build
.PHONY : CPUDelayViewer_autogen/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zstd-build/CMakeFiles/clean-all.dir/build.make _deps/zstd-build/CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

#=============================================================================
# Target rules for targets named libzstd_static

# Build rule for target.
libzstd_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libzstd_static
.PHONY : libzstd_static

# fast build rule for target.
libzstd_static/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zstd-build/lib/CMakeFiles/libzstd_static.dir/build.make _deps/zstd-build/lib/CMakeFiles/libzstd_static.dir/build
.PHONY : libzstd_static/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zstd-build/lib/CMakeFiles/uninstall.dir/build.make _deps/zstd-build/lib/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named libzstd_static_autogen

# Build rule for target.
libzstd_static_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libzstd_static_autogen
.PHONY : libzstd_static_autogen

# fast build rule for target.
libzstd_static_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zstd-build/lib/CMakeFiles/libzstd_static_autogen.dir/build.make _deps/zstd-build/lib/CMakeFiles/libzstd_static_autogen.dir/build
.PHONY : libzstd_static_autogen/fast

#=============================================================================
# Target rules for targets named zstd

# Build rule for target.
zstd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstd
.PHONY : zstd

# fast build rule for target.
zstd/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zstd-build/programs/CMakeFiles/zstd.dir/build.make _deps/zstd-build/programs/CMakeFiles/zstd.dir/build
.PHONY : zstd/fast

#=============================================================================
# Target rules for targets named zstdcat

# Build rule for target.
zstdcat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstdcat
.PHONY : zstdcat

# fast build rule for target.
zstdcat/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zstd-build/programs/CMakeFiles/zstdcat.dir/build.make _deps/zstd-build/programs/CMakeFiles/zstdcat.dir/build
.PHONY : zstdcat/fast

#=============================================================================
# Target rules for targets named unzstd

# Build rule for target.
unzstd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unzstd
.PHONY : unzstd

# fast build rule for target.
unzstd/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zstd-build/programs/CMakeFiles/unzstd.dir/build.make _deps/zstd-build/programs/CMakeFiles/unzstd.dir/build
.PHONY : unzstd/fast

#=============================================================================
# Target rules for targets named zstd.1

# Build rule for target.
zstd.1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstd.1
.PHONY : zstd.1

# fast build rule for target.
zstd.1/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zstd-build/programs/CMakeFiles/zstd.1.dir/build.make _deps/zstd-build/programs/CMakeFiles/zstd.1.dir/build
.PHONY : zstd.1/fast

#=============================================================================
# Target rules for targets named zstdgrep.1

# Build rule for target.
zstdgrep.1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstdgrep.1
.PHONY : zstdgrep.1

# fast build rule for target.
zstdgrep.1/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zstd-build/programs/CMakeFiles/zstdgrep.1.dir/build.make _deps/zstd-build/programs/CMakeFiles/zstdgrep.1.dir/build
.PHONY : zstdgrep.1/fast

#=============================================================================
# Target rules for targets named zstdless.1

# Build rule for target.
zstdless.1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstdless.1
.PHONY : zstdless.1

# fast build rule for target.
zstdless.1/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zstd-build/programs/CMakeFiles/zstdless.1.dir/build.make _deps/zstd-build/programs/CMakeFiles/zstdless.1.dir/build
.PHONY : zstdless.1/fast

#=============================================================================
# Target rules for targets named zstdcat.1

# Build rule for target.
zstdcat.1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstdcat.1
.PHONY : zstdcat.1

# fast build rule for target.
zstdcat.1/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zstd-build/programs/CMakeFiles/zstdcat.1.dir/build.make _deps/zstd-build/programs/CMakeFiles/zstdcat.1.dir/build
.PHONY : zstdcat.1/fast

#=============================================================================
# Target rules for targets named unzstd.1

# Build rule for target.
unzstd.1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unzstd.1
.PHONY : unzstd.1

# fast build rule for target.
unzstd.1/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zstd-build/programs/CMakeFiles/unzstd.1.dir/build.make _deps/zstd-build/programs/CMakeFiles/unzstd.1.dir/build
.PHONY : unzstd.1/fast

#=============================================================================
# Target rules for targets named zstd-frugal

# Build rule for target.
zstd-frugal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstd-frugal
.PHONY : zstd-frugal

# fast build rule for target.
zstd-frugal/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zstd-build/programs/CMakeFiles/zstd-frugal.dir/build.make _deps/zstd-build/programs/CMakeFiles/zstd-frugal.dir/build
.PHONY : zstd-frugal/fast

#=============================================================================
# Target rules for targets named zstdmt

# Build rule for target.
zstdmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstdmt
.PHONY : zstdmt

# fast build rule for target.
zstdmt/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zstd-build/programs/CMakeFiles/zstdmt.dir/build.make _deps/zstd-build/programs/CMakeFiles/zstdmt.dir/build
.PHONY : zstdmt/fast

#=============================================================================
# Target rules for targets named zstd_autogen

# Build rule for target.
zstd_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstd_autogen
.PHONY : zstd_autogen

# fast build rule for target.
zstd_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zstd-build/programs/CMakeFiles/zstd_autogen.dir/build.make _deps/zstd-build/programs/CMakeFiles/zstd_autogen.dir/build
.PHONY : zstd_autogen/fast

#=============================================================================
# Target rules for targets named zstd-frugal_autogen

# Build rule for target.
zstd-frugal_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstd-frugal_autogen
.PHONY : zstd-frugal_autogen

# fast build rule for target.
zstd-frugal_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zstd-build/programs/CMakeFiles/zstd-frugal_autogen.dir/build.make _deps/zstd-build/programs/CMakeFiles/zstd-frugal_autogen.dir/build
.PHONY : zstd-frugal_autogen/fast

CPUDelayViewer_autogen/mocs_compilation.o: CPUDelayViewer_autogen/mocs_compilation.cpp.o
.PHONY : CPUDelayViewer_autogen/mocs_compilation.o

# target to build an object file
CPUDelayViewer_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/CPUDelayViewer_autogen/mocs_compilation.cpp.o
.PHONY : CPUDelayViewer_autogen/mocs_compilation.cpp.o

CPUDelayViewer_autogen/mocs_compilation.i: CPUDelayViewer_autogen/mocs_compilation.cpp.i
.PHONY : CPUDelayViewer_autogen/mocs_compilation.i

# target to preprocess a source file
CPUDelayViewer_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/CPUDelayViewer_autogen/mocs_compilation.cpp.i
.PHONY : CPUDelayViewer_autogen/mocs_compilation.cpp.i

CPUDelayViewer_autogen/mocs_compilation.s: CPUDelayViewer_autogen/mocs_compilation.cpp.s
.PHONY : CPUDelayViewer_autogen/mocs_compilation.s

# target to generate assembly for a file
CPUDelayViewer_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/CPUDelayViewer_autogen/mocs_compilation.cpp.s
.PHONY : CPUDelayViewer_autogen/mocs_compilation.cpp.s

DataLoader/cdsdataloader.o: DataLoader/cdsdataloader.cpp.o
.PHONY : DataLoader/cdsdataloader.o

# target to build an object file
DataLoader/cdsdataloader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/DataLoader/cdsdataloader.cpp.o
.PHONY : DataLoader/cdsdataloader.cpp.o

DataLoader/cdsdataloader.i: DataLoader/cdsdataloader.cpp.i
.PHONY : DataLoader/cdsdataloader.i

# target to preprocess a source file
DataLoader/cdsdataloader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/DataLoader/cdsdataloader.cpp.i
.PHONY : DataLoader/cdsdataloader.cpp.i

DataLoader/cdsdataloader.s: DataLoader/cdsdataloader.cpp.s
.PHONY : DataLoader/cdsdataloader.s

# target to generate assembly for a file
DataLoader/cdsdataloader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/DataLoader/cdsdataloader.cpp.s
.PHONY : DataLoader/cdsdataloader.cpp.s

DataLoader/dataloader.o: DataLoader/dataloader.cpp.o
.PHONY : DataLoader/dataloader.o

# target to build an object file
DataLoader/dataloader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/DataLoader/dataloader.cpp.o
.PHONY : DataLoader/dataloader.cpp.o

DataLoader/dataloader.i: DataLoader/dataloader.cpp.i
.PHONY : DataLoader/dataloader.i

# target to preprocess a source file
DataLoader/dataloader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/DataLoader/dataloader.cpp.i
.PHONY : DataLoader/dataloader.cpp.i

DataLoader/dataloader.s: DataLoader/dataloader.cpp.s
.PHONY : DataLoader/dataloader.s

# target to generate assembly for a file
DataLoader/dataloader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/DataLoader/dataloader.cpp.s
.PHONY : DataLoader/dataloader.cpp.s

InstViewer/instdialog.o: InstViewer/instdialog.cpp.o
.PHONY : InstViewer/instdialog.o

# target to build an object file
InstViewer/instdialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/InstViewer/instdialog.cpp.o
.PHONY : InstViewer/instdialog.cpp.o

InstViewer/instdialog.i: InstViewer/instdialog.cpp.i
.PHONY : InstViewer/instdialog.i

# target to preprocess a source file
InstViewer/instdialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/InstViewer/instdialog.cpp.i
.PHONY : InstViewer/instdialog.cpp.i

InstViewer/instdialog.s: InstViewer/instdialog.cpp.s
.PHONY : InstViewer/instdialog.s

# target to generate assembly for a file
InstViewer/instdialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/InstViewer/instdialog.cpp.s
.PHONY : InstViewer/instdialog.cpp.s

InstViewer/instlabelitem.o: InstViewer/instlabelitem.cpp.o
.PHONY : InstViewer/instlabelitem.o

# target to build an object file
InstViewer/instlabelitem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/InstViewer/instlabelitem.cpp.o
.PHONY : InstViewer/instlabelitem.cpp.o

InstViewer/instlabelitem.i: InstViewer/instlabelitem.cpp.i
.PHONY : InstViewer/instlabelitem.i

# target to preprocess a source file
InstViewer/instlabelitem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/InstViewer/instlabelitem.cpp.i
.PHONY : InstViewer/instlabelitem.cpp.i

InstViewer/instlabelitem.s: InstViewer/instlabelitem.cpp.s
.PHONY : InstViewer/instlabelitem.s

# target to generate assembly for a file
InstViewer/instlabelitem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/InstViewer/instlabelitem.cpp.s
.PHONY : InstViewer/instlabelitem.cpp.s

InstViewer/instrow.o: InstViewer/instrow.cpp.o
.PHONY : InstViewer/instrow.o

# target to build an object file
InstViewer/instrow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/InstViewer/instrow.cpp.o
.PHONY : InstViewer/instrow.cpp.o

InstViewer/instrow.i: InstViewer/instrow.cpp.i
.PHONY : InstViewer/instrow.i

# target to preprocess a source file
InstViewer/instrow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/InstViewer/instrow.cpp.i
.PHONY : InstViewer/instrow.cpp.i

InstViewer/instrow.s: InstViewer/instrow.cpp.s
.PHONY : InstViewer/instrow.s

# target to generate assembly for a file
InstViewer/instrow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/InstViewer/instrow.cpp.s
.PHONY : InstViewer/instrow.cpp.s

InstViewer/instscene.o: InstViewer/instscene.cpp.o
.PHONY : InstViewer/instscene.o

# target to build an object file
InstViewer/instscene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/InstViewer/instscene.cpp.o
.PHONY : InstViewer/instscene.cpp.o

InstViewer/instscene.i: InstViewer/instscene.cpp.i
.PHONY : InstViewer/instscene.i

# target to preprocess a source file
InstViewer/instscene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/InstViewer/instscene.cpp.i
.PHONY : InstViewer/instscene.cpp.i

InstViewer/instscene.s: InstViewer/instscene.cpp.s
.PHONY : InstViewer/instscene.s

# target to generate assembly for a file
InstViewer/instscene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/InstViewer/instscene.cpp.s
.PHONY : InstViewer/instscene.cpp.s

InstViewer/instviewport.o: InstViewer/instviewport.cpp.o
.PHONY : InstViewer/instviewport.o

# target to build an object file
InstViewer/instviewport.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/InstViewer/instviewport.cpp.o
.PHONY : InstViewer/instviewport.cpp.o

InstViewer/instviewport.i: InstViewer/instviewport.cpp.i
.PHONY : InstViewer/instviewport.i

# target to preprocess a source file
InstViewer/instviewport.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/InstViewer/instviewport.cpp.i
.PHONY : InstViewer/instviewport.cpp.i

InstViewer/instviewport.s: InstViewer/instviewport.cpp.s
.PHONY : InstViewer/instviewport.s

# target to generate assembly for a file
InstViewer/instviewport.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/InstViewer/instviewport.cpp.s
.PHONY : InstViewer/instviewport.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPUDelayViewer.dir/build.make CMakeFiles/CPUDelayViewer.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... CPUDelayViewer_autogen"
	@echo "... clean-all"
	@echo "... libzstd_static_autogen"
	@echo "... uninstall"
	@echo "... unzstd"
	@echo "... unzstd.1"
	@echo "... zstd-frugal_autogen"
	@echo "... zstd.1"
	@echo "... zstd_autogen"
	@echo "... zstdcat"
	@echo "... zstdcat.1"
	@echo "... zstdgrep.1"
	@echo "... zstdless.1"
	@echo "... zstdmt"
	@echo "... CPUDelayViewer"
	@echo "... libzstd_static"
	@echo "... zstd"
	@echo "... zstd-frugal"
	@echo "... CPUDelayViewer_autogen/mocs_compilation.o"
	@echo "... CPUDelayViewer_autogen/mocs_compilation.i"
	@echo "... CPUDelayViewer_autogen/mocs_compilation.s"
	@echo "... DataLoader/cdsdataloader.o"
	@echo "... DataLoader/cdsdataloader.i"
	@echo "... DataLoader/cdsdataloader.s"
	@echo "... DataLoader/dataloader.o"
	@echo "... DataLoader/dataloader.i"
	@echo "... DataLoader/dataloader.s"
	@echo "... InstViewer/instdialog.o"
	@echo "... InstViewer/instdialog.i"
	@echo "... InstViewer/instdialog.s"
	@echo "... InstViewer/instlabelitem.o"
	@echo "... InstViewer/instlabelitem.i"
	@echo "... InstViewer/instlabelitem.s"
	@echo "... InstViewer/instrow.o"
	@echo "... InstViewer/instrow.i"
	@echo "... InstViewer/instrow.s"
	@echo "... InstViewer/instscene.o"
	@echo "... InstViewer/instscene.i"
	@echo "... InstViewer/instscene.s"
	@echo "... InstViewer/instviewport.o"
	@echo "... InstViewer/instviewport.i"
	@echo "... InstViewer/instviewport.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/lizilin/projects/CPUStallSim/thirdparty/CPUDelayViewer/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

